import propsData from './props.json';

type Row = { name: string; type: string; required: boolean; default?: string; description: string };

/** Static prop-reference table generated by `npm run extract:props`. */
export function PropsTable({ name }: { name: string }) {
  const rows = (propsData as Record<string, Row[]>)[name];
  if (!rows?.length) return null;
  return (
    <table>
      <thead>
        <tr><th>Prop</th><th>Type</th><th>Default</th><th>Description</th></tr>
      </thead>
      <tbody>
        {rows.map((r) => (
          <tr key={r.name}>
            <td><code>{r.name}{r.required ? '' : '?'}</code></td>
            <td><code>{r.type}</code></td>
            <td>{r.default ? <code>{r.default}</code> : '—'}</td>
            <td>{r.description || ''}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}
